### ISSUE TITLE
Create Script to organise dirs

### ISSUE THREAD

**Issue by maxice8** [maxice8/dotfiles#1]
Create a simple posix shellscript to create and remove dirs to match my ideal organisation) 

/home/$USER 
 |
 | - - tmp (downloads) 
 | - - etc (configuration) 
 | - - var (variable files for user apps) 
 | - - bin (scripts for the user) 
 | - - share (shared data) 
 | - - src (source code for programs) 
 | - - suck (things that suck)

**Comment by casualpleb** [comment]
send nudes bby

**Comment by casualpleb** [comment]
#!/bin/sh


BINFILES="$(find "${HOME}"/* -perm /u=x,g=x,o=x)"
BINLOC="${HOME}/bin"

SRCFILES="$(find "${HOME}"/* | egrep '.tar.gz|.tar.bz2')" 
SRCLOC="${HOME}/src"



binmv() { 
    SAVEIFS="${IFS}"
    IFS="$(/bin/echo -en "\n\b")"
    for f in ${BINFILES}
        do printf %s\\n "Moving ${f} to ${BINLOC}"
        sleep 0.05
    done
}


srcmv() { 
    SAVEIFS="${IFS}"
    IFS="$(/bin/echo -en "\n\b")"
    for f in ${SRCFILES}
        do printf %s\\n "Moving ${f} to ${SRCLOC}"
        sleep 0.05
    done
}

srcmv
binmv


I have this so far

**Comment by maxice8** [comment]
@casualpleb 

Looks great, there isn't any need to do those operations on other sections. 

etc (are on /dotfiles and are managed by stow) 
share (are things that I have backups, like music) 
var (are things the programs create) 
tmp (is on RAM, it is just for downloads and force me to move it)
